name: CD

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Many color libraries just need this to be set to any value, but at least
  # one distinguishes color depth, where "3" -> "256-bit color".
  FORCE_COLOR: 3

jobs:
  dist:
    name: Distribution build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate artifact attestation for sdist and wheel
        uses: actions/attest-build-provenance@bdd51370e0416ac948727f861e03c2f05d32d78e # v1.3.2
        with:
          subject-path: "dist/cuda-histogram-*"

      - uses: hynek/build-and-inspect-python-package@v2

  publish:
    needs: [dist]
    name: Publish to PyPI
    environment:
      name: pypi
      url: https://pypi.org/p/cuda-histogram
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - name: List distributions to be deployed
        run: ls -l dist/

      - name: Verify sdist artifact attestation
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh attestation verify dist/cuda-histogram-*.tar.gz --repo ${{
          github.repository }}

      - name: Verify wheel artifact attestation
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh attestation verify dist/cuda-histogram-*.whl --repo ${{
          github.repository }}

      - uses: pypa/gh-action-pypi-publish@release/v1
